name: Fetch pinball country stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:23 every Monday
    - cron: '23 0 * * 1'

permissions:
  contents: write # So this job can commit changes

jobs:
  fetch-country-stats-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install OS packages needed for R-packages to build from source
        run: sudo apt-get install -y libcurl4-openssl-dev 
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
    
      - name: Install R renv dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Run R script
        run: Rscript get-countries-json.R

      # - name: Commit and Push changes
      #   run: |
      #     git config --global user.name 'Rasmus Bååth'
      #     git config --global user.email 'rasmus.baath@gmail.com'
      #     git add .
      #     git commit -m "Update data files" || echo "No changes to commit"
      #     git push